image:
  - Visual Studio 2015
before_build:
  - cmd: premake.bat
  
platform:
  - Win32
  - x64

configuration: 
  - Release
#  - Debug

after_build:
  - cmd: 7z a -tzip SQLite3-Encryption_%platform%-v%APPVEYOR_BUILD_VERSION%.zip bin/ -xr@x_fn.txt
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
   release: SQLite3-Encryption-v%APPVEYOR_BUILD_VERSION%
   description: "update sqlite3 to v3.23.1"
   provider: GitHub
   auth_token:
    secure: YiRkHuWnabCRwdYGhwkPZRSUJmVb/UeKn3YEQ+0mLTfIsGKrVUfDKdObe/MsYf1A
   draft: false
   prerelease: false
   on:
      branch: master
#   appveyor_repo_tag: false

on_success:
- ps: >-
    if ($true)

    {
      Write-Host "Success"
    }
